import { Platform, StyleSheet } from 'react-native';

export const homeScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  contentContainer: {
    flexGrow: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: Platform.OS === 'ios' ? 95 : 40,
    paddingBottom: 20,
    paddingHorizontal: 24,
  },
  logo: {
    width: 40,
    height: 40,
    marginRight: 10,
  },
  headerTextContainer: {
    flex: 1,
  },
  title: {
    fontFamily: 'YdestreetL',
    fontSize: 24,
    fontWeight: 'bold',
    color: '#222222',
    marginBottom: 5,
  },
  subtitle: {
    fontFamily: 'PretendardBold',
    fontWeight: 'bold',
    fontSize: 32,
    color: '#22222',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 30,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 16,
    width: '48%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  uploadButton: {
    backgroundColor: '#4299e1',
  },
  cameraButton: {
    backgroundColor: '#48bb78',
  },
  buttonText: {
    fontFamily: 'GmarketSansMedium',
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  imagesSection: {
    marginTop: 10,
  },
  sectionTitle: {
    fontFamily: 'GmarketSansBold',
    fontSize: 20,
    fontWeight: '600',
    color: '#2d3748',
    marginBottom: 15,
    paddingHorizontal: 20,
  },
  imagesScrollContainer: {
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  imageWrapper: {
    shadowRadius: 3,
    elevation: 3,
    position: 'relative',
    marginRight: 10,
    width: 120,
  },
  imageThumbnail: {
    width: 120,
    height: 120,
    borderRadius: 16,
    backgroundColor: '#e0e0e0',
  },
  loadingOverlayThumb: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 16,
  },
  summarySection: {
    flex: 1,
  },
  mediaUploadContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  imageUploadButton: {
    paddingVertical: 82,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F5F5',
    marginTop: 24,
    marginHorizontal: 36,
  },
  imageUploadButtonText: {
    fontFamily: 'PretendardMedium',
    color: '#8E8E8E',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 8,
    textAlign: 'center',
  },
  getInfoButton: {
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#46B876',
    marginTop: 36,
    marginHorizontal: 36,
  },
  getInfoButtonText: {
    fontFamily: 'PretendardMedium',
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  getInfoButtonDisabled: {
    backgroundColor: '#EFEFEF',
  },
  getInfoButtonTextDisabled: {
    color: '#888888',
  },
  videoUploadButton: {
    flex: 1,
    paddingVertical: 20,
    paddingHorizontal: 10,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
    backgroundColor: '#F5F5F5',
  },
  videoUploadButtonText: {
    fontFamily: 'PretendardMedium',
    color: '#8E8E8E',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 8,
    textAlign: 'center',
  },
  imageTouchable: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewImage: {
    width: '90%',
    height: '70%',
    borderRadius: 16,
  },
  deleteButton: {
    position: 'absolute',
    top: 5,
    right: 5,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 16,
    padding: 5,
    zIndex: 10,
  },
  modalCloseButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 20,
    right: 20,
    zIndex: 20,
    padding: 10,
  },
  sheetModal: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  // 미디어 프리뷰 관련 스타일
  mediaPreviewContainer: {
    marginTop: 24,
    marginHorizontal: 36,
    borderRadius: 16,
    backgroundColor: '#F5F5F5',
    padding: 16,
  },
  mediaPreviewScrollContainer: {
    paddingVertical: 10,
  },
  mediaPreviewWrapper: {
    marginRight: 10,
    borderRadius: 16,
    overflow: 'hidden',
    width: 120,
    height: 120,
  },
  mediaPreviewTouchable: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
    overflow: 'hidden',
  },
  mediaPreviewImage: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },
  addMoreMediaButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    marginTop: 10,
  },
  addMoreMediaText: {
    fontFamily: 'PretendardMedium',
    color: '#4299e1',
    fontSize: 14,
    marginLeft: 5,
  },
  // 정보 결과 관련 스타일
  infoContainerTitle: {
    fontFamily: 'PretendardSemiBold',
    fontSize: 16,
    color: '#222222',
    marginHorizontal: 36,
    marginTop: 33,
  },
  infoResultContainer: {
    marginTop: 20,
    marginHorizontal: 36,
    marginBottom: 30,
    padding: 15,
    backgroundColor: '#f5f5f5',
    borderRadius: 16,
  },
  infoResultScrollView: {
    maxHeight: 300,
  },
  infoResultText: {
    fontFamily: 'PretendardMedium',
    fontSize: 14,
    color: '#3d3d3d',
    lineHeight: 20,
  },
  // 로딩 애니메이션 스타일
  loadingWaveContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingBar: {
    width: 4,
    height: 20,
    backgroundColor: '#FFFFFF',
    marginHorizontal: 2,
    borderRadius: 4,
  },
  // 답변 로딩 스타일
  answerLoadingContainer: {
    marginTop: 20,
    marginHorizontal: 36,
    padding: 15,
    backgroundColor: '#f5f5f5',
    borderRadius: 16,
  },
  answerLoadingBar: {
    height: 16,
    backgroundColor: '#CACACA',
    borderRadius: 4,
    marginBottom: 16,
  },
  answerLoadingBarShort: {
    width: '60%',
  },
  answerLoadingBarMedium: {
    width: '80%',
  },
  answerLoadingBarLong: {
    width: '90%',
  },
  // Image Analysis Styles
  loadingContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#666',
  },
  analysisContainer: {
    padding: 20,
    backgroundColor: '#fff',
    borderRadius: 12,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  analysisTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
    color: '#333',
  },
  analysisSection: {
    marginBottom: 20,
  },
  analysisSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
    color: '#444',
  },
  resultText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#666',
  },
  objectItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    marginBottom: 8,
  },
  selectedObjectItem: {
    backgroundColor: '#fff0f0',
    borderColor: '#ff3b30',
    borderWidth: 1,
  },
  objectName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
  },
  objectConfidence: {
    fontSize: 12,
    color: '#666',
  },
  labelItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    marginBottom: 8,
  },
  labelText: {
    fontSize: 14,
    color: '#333',
  },
  labelConfidence: {
    fontSize: 12,
    color: '#666',
  },
  objectLabel: {
    position: 'absolute',
    top: -20,
    left: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  objectLabelText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '500',
  },
  // Task Suggestions Styles
  taskSuggestionsContainer: {
    marginTop: 20,
    marginHorizontal: 36,
    padding: 15,
    backgroundColor: '#f5f5f5',
    borderRadius: 16,
  },
  taskSuggestionsTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 16,
    color: '#333',
  },
  taskSuggestionItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 15,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  taskSuggestionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  taskSuggestionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    flex: 1,
  },
  priorityBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 8,
  },
  priorityText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '500',
  },
  taskSuggestionDescription: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
});