  import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    paddingBottom: Platform.OS === 'android' ? 20 : 0,
  },
  selectorButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#f5f5f5',
  },
  iconCircle: {
    width: 13,
    height: 13,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedTypeText: {
    fontSize: 13,
    fontFamily: 'PretendardMedium',
    textAlign: 'left',
    flex: 1,
  },
  modal: {
    margin: 0,
    justifyContent: 'flex-end',
  },
  modalContentContainer: {
    backgroundColor: 'white',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: '80%',
    paddingBottom: 50,
  },
  swipeIndicator: {
    width: 50,
    height: 4,
    backgroundColor: '#8E8E8E',
    borderRadius: 1.5,
    alignSelf: 'center',
    marginTop: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 24,
    paddingBottom: 16,
    paddingHorizontal: 35,
  },
  modalTitle: {
    fontFamily: 'PretendardSemiBold',
    fontSize: 22,
    color: '#222222',
  },
  modalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 35,
  },
  modalItemSelected: {
    backgroundColor: '#f8f8f8',
  },
  itemIconCircle: {
    width: 18,
    height: 18,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  modalItemText: {
    fontFamily: 'PretendardMedium',
    fontSize: 16,
    color: '#222222',
    flex: 1,
  },
  ocrLoadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  ocrLoadingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#fff',
  },
});